#!/bin/bash
# Shane E Gordon
# Fri Feb 14 13:45:58 EST 2014
# v1.01

# ChangeLog
# v1.01 - The initial 0.5 ns of simulations (opt.[something]) is no longer included when reading DCD files. This removes some non-equilibrium effects that may hinder clustering methods in MSMBuilder.

# This script functions to align each protein atoms from each trajectory series with a common PDB template, "reference.pdb", which should be placed in the base folder. Trajectories are then written out with only protein atoms and one of any ligands in the system with the RESNAME of "LIG" to a new folder, "Protein_OneLigand", under the name of their original directory.

if [ -d Protein_OneLigand ]
then
	read -p "Directory Protein_OneLigand already exists. Overwrite (Yes/No)?" choice
	case "$choice" in 
		  yes|Yes ) echo "Okay...";;
		  no|No ) echo "Right, no"; 
		    exit;;
		    * ) echo "invalid";;
	      esac
	
	rm -r Protein_OneLigand
	mkdir Protein_OneLigand
else 
	mkdir Protein_OneLigand
	echo "Directory 'Protein_OneLigand' not found; making new directory"
fi

for i in *_pyr; do (
	cd ./$i; 
	echo "source ../Analysis/Tools/analysis.tcl
mol new ../reference.pdb
fitagainst 1 0 protein
# Writes trajectories with protein and just one ligand
set lig1 [atomselect 0 \"resname LIG and resid 1\"]
set liga [atomselect 0 \"resname LIG\"]
set nlig1 [\$lig1 num]
set nliga [\$liga num]
set m [expr \$nliga / \$nlig1]
cd ../Protein_OneLigand
# mkdir ${i}
# cd ${i}
for { set k 1 } { \$k <= \$m } { incr k } {
set sel1 [atomselect 0 \"noh resname LIG and resid \$k or protein\"]
\$sel1 writepsf ${i}.fitted.resid_\${k}.psf
animate write dcd ${i}.fitted.resid_\${k}.dcd beg 0 sel \$sel1 waitfor all 0}
exit" > fitscript.tcl; 
echo "*****Now processing $i*****"; 
/usr/local/vmd/1.9.1/bin/vmd InputFiles/ionized.psf OutputFiles/2[0-9]*.dcd -dispdev text -e fitscript.tcl; 
rm fitscript.tcl
); 
done

