#!/bin/bash
# Shane E Gordon
# Fri Feb  7 09:19:17 EST 2014
# v1.01

# Converts ligand data to trr file format for later conversion to XTC

if [ -d XTC ]
then
        read -p "Directory XTC already exists. Overwrite (Yes/No)?" choice
        case "$choice" in
                yes|Yes ) echo "Okay...";;
                no|No ) echo "Right, no";
                exit;;
                * ) echo "invalid";;
        esac
        rm -r XTC
        mkdir XTC
else
        mkdir XTC
fi
sleep 2

if [ -d Protein_OneLigand ]
then
	cd ./Protein_OneLigand
	for MDDir in *.dcd; do (
	../Analysis/Tools/catdcd -otype trr -o $MDDir.trr $MDDir
        );
done
else
       	echo "Protein_OneLigand directory not found! Be sure to generate this first"
	exit
fi    

mv *.trr ../XTC
cd ../XTC
for XTCMDDir in *; 
do (
	/usr/local/gromacs/4.6.5-intel/bin/trjconv -f $XTCMDDir -o $XTCMDDir.xtc
	); 
done
rm *.trr
for TRRMDDir in *; 
do (
	mkdir RUN4_$TRRMDDir; mv $TRRMDDir RUN4_$TRRMDDir
	); 
done
