#!/bin/bash

if [ -d extracted_protein ]
then
        read -p "Directory extracted_protein already exists. Overwrite (Yes/No)?" choice
        case "$choice" in 
                yes|Yes ) echo "Okay...";;
                no|No ) echo "Right, no"; 
                exit;;
                * ) echo "invalid";;
        esac
        rm -r extracted_protein
        mkdir extracted_protein
else 
        mkdir extracted_protein                                                                              
        echo "Directory 'extracted_protein' not found; making new directory"
fi
for i in *ns_pyr; do (cd $i; echo "source ~/analysis.tcl
        mol new ../reference.pdb
        fitagainst 1 0 protein
        # Writes out fitted frames to a new DCD file
        cd ../extracted_protein
        set sel2 [atomselect 0 \"noh resname LIG or noh protein\"]
        \$sel2 writepsf ${i}.psf
        animate write dcd ${i}.fitted.protein.lig.dcd beg 0 sel \$sel2 waitfor all 0
        mkdir ${i}
        mv ${i}.fitted.protein.lig.dcd ./${i}
        mv ${i}.psf ./${i}
        # set lig1 [atomselect 0 \"resname LIG and resid 1\"]
        # set liga [atomselect 0 \"resname LIG\"]
        # set nlig1 [\$lig1 num]
        # set nliga [\$liga num]
        # set m [expr \$nliga / \$nlig1]
        # cd ../fitted_ligands
        # for { set k 1 } { \$k <= \$m } { incr k } {
        #        set sel1 [atomselect 0 \"resname LIG and resid \$k and not protein\"]
        #        animate write dcd ${i}.fitted.resid_\${k}.dcd beg 0 sel \$sel1 waitfor all 0}
        exit" > fitscript.tcl; echo "**********Now processing $i**************"; 
        /usr/local/vmd/1.9.1/bin/vmd InputFiles/ionized.psf OutputFiles/2013*.dcd -dispdev text -e ./fitscript.tcl; 
        rm fitscript.tcl
        ); 
done
